### ISSUE TITLE
Could we release a v1?

### ISSUE THREAD

**Issue by kellyselden** [validated-changeset/validated-changeset#132]

**Comment by snewcomer** [comment]
Yes.  That seems like a great idea.  Have been hesitant b/c I have been eager to get proper Ember Dat support with this library but many of the changes seem likely to occur in ember-changeset.  I'll make sure I prioritize this before Ember 4.0 release.

**Comment by kellyselden** [comment]
IMO you shouldn't put that much importance in the number 1. You could v1 it right now, then v2 it whenever you need to break it again.

**Comment by snewcomer** [comment]
Point taken!  1.0.0 released.

**Comment by kellyselden** [comment]
Thanks Scott!
