### ISSUE TITLE
rollbackInvalid removes valid changes

### ISSUE THREAD

**Issue by vstefanovic97** [validated-changeset/validated-changeset#177]
Steps to reproduce
1. Create nested property on a changeset
2. Make it fail validation
3. Set it to a valid value and validate
4. Call `rollbackInvalid()`
5. Observe that the now valid property had been removed from the changesets `changes`.

I have created a PR with a fix for this, also added a test case that can be reviewed for reproduction (without the fix the test will fail)
https://github.com/validated-changeset/validated-changeset/pull/176

**Comment by snewcomer** [comment]
1.3.3!
