### ISSUE TITLE
Error validating async BelongsTo relationship

### ISSUE THREAD

**Issue by urbany** [validated-changeset/validated-changeset#19]
Hi, I'm getting an error in this line https://github.com/validated-changeset/validated-changeset/blob/22aa5e08038cc82d733ae248af931503eee32482/src/index.ts#L197

Uncaught TypeError: Converting circular structure to JSON
![Screenshot 2020-03-09 at 18 06 56](https://user-images.githubusercontent.com/50884/76243820-d9306080-6230-11ea-837e-a52b1f276fc6.png)

Using latest release version of ember-changeset and ember-changeset-validations
This is the validation rule

```js
category: validatePresence(true),
```

And this is how the category is defined in the model:

```js
@belongsTo('product-category') category
```

**Comment by urbany** [comment]
The problem is caused by category being an async relationship, which means error.value is an ProxyObject, and looks like `JSON.stringify(proxyObjectHere)` throws that error, maybe the best solution is to unwrap the proxyobject on `changeset.addError` ?

**Comment by snewcomer** [comment]
@urbany Seems like you are right!  How do you propose we modify `addError`?  (Feel free to put up a PR if you would like!)

**Comment by ohcibi** [comment]
I had the same error with a `hasMany` relation ship where `error.property.value.constructor` is `DS.PromiseManyArray` which is a promise. So a change to `.addError` would require it to return a promise itself. This goes a few steps up in the callstack and a bunch of (mostly internal) functions would need to become async. I'm not so sure if this is desired. The functions in question would be:

* addError
  * _handleValidation
    * _validateKey (which seems to be promise aware already)
    * setUnknownProperty
      * set (I guess from here we go nuts?) 

On the other hand there is already a comment that asks `why` the parsing back and forth is happening here. Maybe this can be solved differently and unwrapping the value becomes entirely unnecessary?

**Comment by ohcibi** [comment]
I made a suggestion for making the `value` immutable without stringifying and parsing to and from JSON which I'd like to share here. The idea is to store a proxied reference as `value` in the `error.<property>` object, that has a noop setter and a getter that again wraps the `get`ed value in a proxy if its an object.

```typescript
const handler = {
  get(obj, prop) {
    return typeof obj[prop] === 'object' ? new Proxy(obj[prop], handler) : obj[prop];
  },
  set() {}
};

```
and then in `addError`:
```typescript
const value = new Proxy(theValue, handler);
```
