### ISSUE TITLE
When nested value become null an error occurs

### ISSUE THREAD

**Issue by basz** [validated-changeset/validated-changeset#51]
https://github.com/validated-changeset/validated-changeset/blob/d77178140fb3dcfa2bf227d4fc07ea2a9ae463d7/src/utils/set-deep.ts#L15

This happens because this conditional will pass when value equals null https://github.com/validated-changeset/validated-changeset/blob/master/src/utils/set-deep.ts#L69

Can see it happen [here](https://ember.bushbaby.nl) [source](https://github.com/basz/ember-form) (with the second control)... 

After some console debugging i found the setDeep is called with a validation error object? Removing validation "solves" that but does not change the described issue...

```
// function setDeep(target, path, value, options) {
//    console.log(target, path, value, options);


{} "child.prop" Change {value: "2"} {safeSet: ƒ}
{child: {…}} "child.prop" Change {value: "1"} {safeSet: ƒ}
{child: {…}} "child.prop" Change {value: null} {safeSet: ƒ}
{} "child.prop" Err {value: null, validation: Array(1)} {safeSet: ƒ}
{child: {…}} "child.prop" Change {value: "2"} {safeSet: ƒ}
```

**Comment by basz** [comment]
changing https://github.com/validated-changeset/validated-changeset/blob/master/src/utils/set-deep.ts#L69 into 

```
if (typeof target[prop].value === 'object' && target[prop].value !== null)
```

seems to avoid the Object.keys(null) problem, but since i have no idea what i'm doing here i'll leave the solution up to you... ;-)

here's the full error btw
```
validated-changeset.es5.js:858 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at findSiblings (validated-changeset.es5.js:858)
    at Proxy.setDeep (validated-changeset.es5.js:915)
    at Proxy.BufferedChangeset._setProperty (validated-changeset.es5.js:2258)
    at Proxy._setProperty (index.js:94)
    at Proxy.BufferedChangeset.setUnknownProperty (validated-changeset.es5.js:1707)
    at Proxy.BufferedChangeset.set (validated-changeset.es5.js:2471)
    at ApplicationController.<anonymous> (changeset-set.js:19)
    at Backburner._join (backburner.js:995)
    at Backburner.join (backburner.js:760)
```

**Comment by basz** [comment]
hmm, the full condition should be `if (isObject(target[prop].value))` ???

**Comment by snewcomer** [comment]
isObject is correct!  Nice find and PR welcome if you would like.  Thanks!!

**Comment by basz** [comment]
sure... np

**Comment by snewcomer** [comment]
Thank you!!
