### ISSUE TITLE
Nested set changes not forwarded back into ember-bootstrap control

### ISSUE THREAD

**Issue by basz** [validated-changeset/validated-changeset#56]
Q; 'm seeing an issue for with I think I am doing everything correct. (Note the *think*) :-)

I would really appreciate some eyes on this demo application which shows the issue. It might be that the latest refactoring caused this but I'm hoping that intimate knowledge of the internals of this package brings on an aha moment. I'm not seeing it :-/

https://ember.bushbaby.nl
https://github.com/basz/ember-form

note that at first, I thought it had something to do with ember-data-model-fragment (also refactored) but I've since ruled that out.

**Comment by snewcomer** [comment]
What are some of the issues you are having?

**Comment by basz** [comment]
Given I have a changeset and a bs-form with `@model={{this.changeset}}` changed values are only updated *back* into the control ONCE. After changing the value once it stops updating...

**Comment by snewcomer** [comment]
Is it changing back to an original value or to a new value?

**Comment by basz** [comment]
look at 'value in element: "undefined" inside the orange bit... That's the value from the control comming from the 'outside'. An action changes the value in the changeset it should go to the control also to update it's internal state.

https://github.com/basz/ember-form/blob/master/app/templates/application.hbs#L121

**Comment by snewcomer** [comment]
I'm unable to install ember-data.model-fragments. 🤔

**Comment by basz** [comment]
beta was released, and the branch deleted... I've updated

**Comment by basz** [comment]
not relevant anymore
