### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by basz** [validated-changeset/validated-changeset#59]
I wrote this test which is failing but should pass I believe.

```
it('Should return full object', () => {
    const model = {
      xxx: {
        rgt: {len: 10},
        lft: {len: 11}
      }
    };
    const changeset = Changeset(model);

    const expectedResult = {
      rgt: {len: 10},
      lft: {len: 11}
    };
    expect(changeset.get('xxx')).toEqual(expectedResult);
    expect(changeset.get('xxx.rgt')).toEqual(expectedResult.rgt);
  });
```

```
    - Expected
    + Received

    - Object {
    -   "lft": Object {
    -     "len": 11,
    -   },
    -   "rgt": Object {
    -     "len": 10,
    -   },
    - }
    + Object {}
```

**Comment by snewcomer** [comment]
@basz Thanks for the issue again!  So your tests are failing b/c we still detect that you may need to continue traversing down the object tree until you reach a primitive, thus returning you a Proxy object instead of the raw value for `xxx.rgt`...  See link below.  A test like this would be what you are looking for.

`expect(changeset.get('xxx.rgt.len')).toEqual(expectedResult.rgt.len);`

https://github.com/validated-changeset/validated-changeset/blob/31e8b16d733d962d1f3e16ef4060e2d8c07bb494/src/index.ts#L908

In my use cases, I never needed an intermediate value until I reached a leaf node.  The only use case I could think of is equality comparison or something.  Do you have a use case in mind?

**Comment by basz** [comment]
I definitely feel I would like to be able to work with non primitives.

I have many properties values that are actually pojo value objects. Eg a meassurementSession has a left and right proponent each with several measuring points... or the configuration of a an insole with also has up to 5 attributes.

These are stored in a value property on polymorphic ember data models and modified in the ui with specialized form components (eg. Take each measurement and ensure that it’s a in a valid state depending on some outside variants) that take in these pojo’s by accessing the root properties of the changeset and thus are expecting objects... the form validators are also specialized and expect to be able to retrieve inspect pojo values.

Would it be hard/difficult for the changeset to return  {y: {z: 3 } } for a model of x.y.z = 3 when I ask for x?

I could work with a json strings since they are primitives but that would mean lots of refactoring in our app and feels counter intuitive...

Sorry this a bit domain specific but I hope I can make my case... this used to work ok as fast as I can remember.

Of course I would be willing to put in some work here - feels the decent thing to offer - but would need guidance on how to achieve that... even if it means to improve docs saying It only works with primitives...

Thanks Scott

**Comment by basz** [comment]
Just doodling now but doesn’t ‘mergeDeep(content, changes)’ already creates a POJO we could use to get values from any path from?

**Comment by snewcomer** [comment]
> for the changeset to return  {y: {z: 3 } }

I added an API to #61 to allow you to do this.

However, I'm still curious on what makes it necessary to access an intermediate node in the object tree other than for equality.  Does your validator compare two objects? 

You can `set` at any level of the object tree.  And once you access a leaf node, you will get back what you expect.

**Comment by basz** [comment]
Do you use forms from ember-bootstraps with ember-changeset? Suppose I have a model of

‘’’
{
  baseKey: payloadForBsElement
}
‘’’

Where payloadForBsElement is a pojo. In other instances it might be a primitive.

The form component gets new Changeset(model) as its model.

The form element get its value from the form model (now a changeset) via the baseKey. Defined by ‘property’ on the form element definition. 

The value it receives may be a proxy but it would like to work with it if it were regular pojo.

(pretty sure my issue from ember.bushbaby.nl come from this)

**Comment by snewcomer** [comment]
@basz if you don't mind pointing me to a production example, that would be great!  I'm having a hard time seeing a use case where you don't "eventually" need to access a leaf value (a primitive) in app code (I can see how a test is useful and would fail though)

**Comment by basz** [comment]
Hmm. playing a lot... This is a bit confusing. First a question... Why can't I console.log(changeset.xxx) when xxx contains a deeper path? That would be so helpful...

Secondly, think I found an issue with ember-bootstrap forms that is acting up... It is using a dynamically created value property that is passed to the component. It does not seem to work reliably with nested keys.

```
defineProperty(this, 'value', alias(`model.${this.property}`));
```

Personally I believe the alias isn't working as expected... an alias does not seem to behave exactly like the real thing.

If I create a modify that code to a getter/setter my problem from ember.bushbaby.nl seems to disappear... So I'll create an issue over there.

And to answer your question... -eventually- got me thinking... Yes, I get it working when accessing primitives, but the things described above seem to have gotten in the way... 

(no more hair left)...

I'll leave this open for now, but I think - with the modification - to ember-bootstrap things are looking good again...

**Comment by snewcomer** [comment]
> Why can't I console.log(changeset.xxx)

It is a Proxy.  See #61 for an API to allow you to see it

**Comment by snewcomer** [comment]
Let me know if you have more questions!
