### ISSUE TITLE
Original exception not propagated in save() with pull request #80

### ISSUE THREAD

**Issue by mikeburg** [validated-changeset/validated-changeset#81]
Pull request #80 which rollbacks the attributes on save() exception does not propagate the original exception and instead creates a new Error exception that loses the server response exception. The http status, and response payload is no longer accessible.

In file index.ts, method save() around line 418 is:
```
throw new Error(e);
```
the line really should be to propagate the exception:
```
throw e;
```

**Comment by snewcomer** [comment]
A PR would be greatly appreciated (and a test fixed).  Otherwise I can do it this week!
