### ISSUE TITLE
Object values returns Proxy instead of value

### ISSUE THREAD

**Issue by Krzema** [validated-changeset/validated-changeset#84]
I'm using ember-changeset package. I'm creating Changeset, which has value as an object - lets say it's:
```
let user = { value1: {id: 1, text: "test"} };
let changeset = Changeset(user, {});
```
When I'm using `changeset.get("value1")` it returns me Proxy instead of object defined in value1. Is it correct behaviour?
In that case, when I'm working with ember-bootstrap and BsForms, element with `@controlType=radio` is not working propertly, when i pass object and optionLabelPath

**Comment by snewcomer** [comment]
It is.  We expect, especially for a form, that you will access the leaf keys.  

https://github.com/poteto/ember-changeset/issues/549

Could you try `user.value1.unwrap()` where this is passed into your controls?

**Comment by snewcomer** [comment]
closing for now!  lmk if you have other questions.
