### ISSUE TITLE
Using `bufferedChangeset.prepare/1` replaces existing values that are proxies with undefined

### ISSUE THREAD

**Issue by jordpo** [validated-changeset/validated-changeset#86]
I am seeing behavior where I am using the `prepare` method on a changeset that has a relationship to another object (e.g. a new user that has a company). Before running this method, `changeset.get('company')` returns the related object. After running this method, this is no longer the case. 

I identified the issue is that `this[CHANGES]` shows the associated object as a change when it should not be a change. You can see it clearly in the example below where `C` is the `BufferedChangeset`. I think this might have something to do with how you handle the nested proxy values?

![image](https://user-images.githubusercontent.com/3884107/96191992-2dac6480-0f13-11eb-8f6f-0d4c8643e559.png)

**Comment by snewcomer** [comment]
@jordpo Thanks for the issue.  How are you dealing with the `company`?  The assumption was most users eventually access the leaf keys (primitives).  Is this not the case for you?  We provided an `unwrap()` method as an escape hatch.  However, if more users than I imagines have valid use cases for not having a proxy, then I might need to rethink this.  Thank you!! 

```
c.get('company').unwrap()
```

**Comment by jordpo** [comment]
So in this case, company is an Ember Data model that we bootstrap on a new user when loading the route. We then wrap the new user in a changeset. The company does not change within the context of the changeset or the form. We just need the company relationship to still exist on the user when the data is serialized for the API. 

I don't think it's a proxy issue since `changeset.get('company')` works fine and returns the object proxy which is what you would expect. From what I can tell, the issue is just that `company` is registered as 'changed' on `changeset._changes' and more troublesome, it's changed new value is `undefined`. This causes the relationship to get overridden when you invoke `changeset.prepare`.

**Comment by snewcomer** [comment]
> does not change within the context of the changeset or the form

So the bug is something like this? -

On initialization of a Changeset, after *some actions taken on the changeset, `company` is showing up in the `changes`?  What are those "actions", if any?

**Comment by jordpo** [comment]
> On initialization of a Changeset, after *some actions taken on the changeset, company is showing up in the changes? What are those "actions", if any?

No actions are needed. If you log `changeset._changes` you would see it present on there.

**Comment by jordpo** [comment]
If you follow the steps in my screenshot, you can reproduce it.

**Comment by snewcomer** [comment]
Great!  Sounds like this might be an easy failing test to add as well.

**Comment by jordpo** [comment]
@snewcomer just opened a PR with a failing test. Also got more clarity on the issue and added my findings in the PR description. https://github.com/validated-changeset/validated-changeset/pull/87

**Comment by snewcomer** [comment]
Included in 3.10.3!
