### ISSUE TITLE
is the unwrap method public api

### ISSUE THREAD

**Issue by basz** [validated-changeset/validated-changeset#88]
I have a situation where I want to unwrap an incoming Proxy to be able to do make snapshot (JSON.stringify(object)) of it.

How everever in some instances the incoming value is a pojo, not a proxy managed by validated changeset. (it becomes managed eventually) So I want to be able to do this basically...

```
var resolvedValue = value instanceof ObjectTreeNode ? value.unwrap() : value;
``` 

Is ObjectTreeNode public? Can I import it? I don't think so. 
Or, ... is there an unwrap function I could export hiding ObjectTreeNode altogether.

**Comment by snewcomer** [comment]
Does this work?

```
var resolvedValue = value.unwrap ? value.unwrap() : value;
```

**Comment by basz** [comment]
Since I am using the following I guess that would work too...


"function" === typeof value.unwrap ? value.unwrap() : value

**Comment by snewcomer** [comment]
Let me know if you have other questions!
