### ISSUE TITLE
Changeset key="set" overwrites the set method of BufferedChangeset

### ISSUE THREAD

**Issue by m3l1x** [validated-changeset/validated-changeset#91]
If the key of a changeset equals to "set", then the set-method of BufferedChangeset gets overwritten. This happens here: https://github.com/validated-changeset/validated-changeset/blob/2ae91628ad1d6c3384e5dd4dd7e9a5406505c084/src/index.ts#L993
The next time the set-method of BufferedChangeset is called, it results in an error.

**Comment by snewcomer** [comment]
@m3l1x 👋  `set` and `get` are restricted keys for the backing object to a Changeset since the changeset and your object become "one" during the lifetime of the changeset.  I don't know if we have another solution to get around this.
